### ISSUE TITLE
URI trailing slash problems

### ISSUE THREAD

**Issue by antonkomarev** [realshadow/satis-control-panel#2]
[ttp://localhost:8000/control-panel](http://localhost:8000/control-panel) output:

> {"result":false,"message":""}

[http://localhost:8000/control-panel/](http://localhost:8000/control-panel/) is working well.

**Comment by antonkomarev** [comment]
I've tried to add some unit tests for API but all the endpoints except `$this->call('GET', '/')` returning me JSON:

> {"result":false,"message":""}

Am I missed something and how to fix it? You can check it out in [unit tests WIP feature](https://github.com/cybercog/satis-control-panel/tree/feature/unit-tests-mockup).

_I haven't started new issue for it because it looks like this is the same thing. Something bad with routing or responses._

**Comment by realshadow** [comment]
This happens because `control-panel` is a _physical  folder_ not a route and thus requires the trailing slash. Normal webserver, e.g. apache automatically adds the trailing slash due to `DirectorySlash` directive. Sadly, `serve` command is a bit limited in emulating full webserver environment and he wont add the trailing slash.

> {"result":false,"message":""}

Happens due to the exception handler which tries to "hide" the exception in environments higher than local (I am not sure why though) and since the default `.env` automatically sets itself to **production** it doesn't show correctly.
